language: c

sudo: true

addons:
  apt_packages:
    - pandoc

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_github jimhester/robustr
  - ./travis-tool.sh install_github jimhester/covr

install:
  - ./travis-tool.sh install_deps
  # Install testthat after running install_deps, otherwise devtools itself might be installed from CRAN or c2d4u

after_success:
  - Rscript -e 'library(covr); coveralls()'
notifications:
  email:
    on_success: change
    on_failure: change
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - BOOTSTRAP_LATEX=1
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran"
